import React from "react";
import { Frame, Logo, palette, fonts } from "./_shared";

// 2048×1152 YouTube channel banner. YouTube crops this hard per device — only
// the centered 1235×338 "safe area" is guaranteed visible (TV shows the full
// 2048×1152). The background is our generated character art (lab full of
// blobs framing an open center); the logo lockup sits in the safe band, over a
// soft scrim that guarantees legibility.
const SAFE_W = 1235;
const SAFE_H = 338;

// Generated by scripts/generate_steam_assets.py (asset: youtube-banner).
const BG = "/refs/generated/youtube-banner.png";

export function YoutubeBanner() {
  return (
    <Frame width={2048} height={1152} background={palette.bg}>
      <img
        src={BG}
        alt=""
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          objectFit: "cover",
          objectPosition: "center",
        }}
      />

      {/* Center scrim — darkens the middle so the logo always reads, fading
          out before the edge characters so they stay vivid. */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          background:
            "radial-gradient(ellipse 46% 62% at 50% 50%, rgba(10,6,18,0.74) 0%, rgba(10,6,18,0.45) 45%, rgba(10,6,18,0) 72%)",
        }}
      />

      {/* Centered safe-area content */}
      <div
        style={{
          position: "absolute",
          left: "50%",
          top: "50%",
          transform: "translate(-50%, -50%)",
          width: SAFE_W,
          height: SAFE_H,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          gap: 24,
        }}
      >
        <Logo size={2.2} />
        <div
          style={{
            fontFamily: fonts.display,
            fontWeight: 800,
            fontSize: 42,
            color: palette.paper,
            letterSpacing: 1,
            textShadow: "0 2px 8px rgba(0,0,0,0.6)",
          }}
        >
          Bounce · Squish · Conquer
        </div>
        <div
          style={{
            marginTop: 2,
            background: palette.accentLavender,
            color: palette.ink,
            fontFamily: fonts.display,
            fontWeight: 900,
            fontSize: 30,
            letterSpacing: 2,
            textTransform: "uppercase",
            padding: "12px 28px",
            borderRadius: 999,
            border: `4px solid ${palette.bg}`,
            transform: "rotate(-1.5deg)",
            boxShadow: "0 6px 16px rgba(0,0,0,0.45)",
          }}
        >
          ▶ New clips daily
        </div>
      </div>
    </Frame>
  );
}
