// Generate fixed-point sin and atan LUTs at build time.
//
// IMPORTANT — determinism note: f64 sin/atan are used here at *build time*
// to compute the LUT entries, which are then baked into the binary as i64
// constants. For true cross-machine determinism every build host must
// produce identical LUTs. In practice glibc/musl/Apple libm/MSVCRT can
// differ by 1 ULP on transcendentals. Phase 2 follow-up: commit the
// generated tables as a checked-in source file and have CI verify a
// SHA-256 of the generated bytes matches a pinned value.

use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;

const FRAC_BITS: u32 = 32;
const FX_ONE: f64 = (1u64 << FRAC_BITS) as f64;

const SIN_LUT_N: usize = 16_384;
const ATAN_LUT_N: usize = 4_096;

fn to_fx(x: f64) -> i64 {
    (x * FX_ONE).round_ties_even() as i64
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("luts.rs");
    let mut w = BufWriter::new(File::create(&out).expect("create luts.rs"));

    writeln!(w, "// Auto-generated by build.rs. Do not edit.").unwrap();
    writeln!(w, "pub const SIN_LUT_N: usize = {};", SIN_LUT_N).unwrap();
    writeln!(w, "pub const ATAN_LUT_N: usize = {};", ATAN_LUT_N).unwrap();

    // SIN_LUT[i] = sin(i / N * 2π) in Fx.
    writeln!(w, "pub static SIN_LUT: [i64; {}] = [", SIN_LUT_N).unwrap();
    for i in 0..SIN_LUT_N {
        let angle = (i as f64) / (SIN_LUT_N as f64) * core::f64::consts::TAU;
        writeln!(w, "    {}i64,", to_fx(angle.sin())).unwrap();
    }
    writeln!(w, "];").unwrap();

    // ATAN_LUT[i] = atan(i / (N-1))  for i in [0, N).
    // Covers the first-octant ratio r = y/x ∈ [0, 1]; full atan2 reduces
    // by quadrant + (y vs x) reflection.
    writeln!(w, "pub static ATAN_LUT: [i64; {}] = [", ATAN_LUT_N).unwrap();
    for i in 0..ATAN_LUT_N {
        let r = (i as f64) / ((ATAN_LUT_N - 1) as f64);
        writeln!(w, "    {}i64,", to_fx(r.atan())).unwrap();
    }
    writeln!(w, "];").unwrap();

    // Bake key fixed-point constants the runtime needs (no float at runtime).
    writeln!(w, "pub const FX_PI: i64        = {};", to_fx(core::f64::consts::PI)).unwrap();
    writeln!(w, "pub const FX_TAU: i64       = {};", to_fx(core::f64::consts::TAU)).unwrap();
    writeln!(w, "pub const FX_PI_OVER_2: i64 = {};", to_fx(core::f64::consts::FRAC_PI_2)).unwrap();
    writeln!(w, "pub const FX_PI_OVER_4: i64 = {};", to_fx(core::f64::consts::FRAC_PI_4)).unwrap();

    // (N / 2π) in Fx — multiply an angle by this to get a LUT-index in Fx.
    let idx_scale = (SIN_LUT_N as f64) / core::f64::consts::TAU;
    writeln!(w, "pub const FX_SIN_INDEX_SCALE: i64 = {};", to_fx(idx_scale)).unwrap();

    w.flush().unwrap();
}
